services:
  wr:
    build: .
    env_file: .env
    ports:
      - "1234:1234"
    volumes:
      - wr-data:/data
    restart: unless-stopped
    # command: ["--enable-dangerous-developer-environment"]
    # network_mode: host

volumes:
  wr-data:
