// Walks the built web directory and writes a C++ source that embeds every file
// as a byte array, with a table from the url path to the bytes. The server
// serves the frontend from this table, so the binary carries the bundle and no
// web root is read from disk. Byte arrays are used rather than the #embed
// directive, since the cosmopolitan toolchain does not accept it.

import fs from "node:fs";
import path from "node:path";

const distDir = process.argv[2];
const outFile = process.argv[3];

if (!distDir || !outFile) {
  console.error("usage: bun gen-embed.js <dist-dir> <out-file>");
  process.exit(1);
}

if (!fs.existsSync(distDir)) {
  console.error(
    "gen-embed: the web build is missing at " +
      distDir +
      ". Run the web build first, for example `make web`.",
  );
  process.exit(1);
}

function walk(dir) {
  const found = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...walk(full));
    } else if (entry.isFile()) {
      found.push(full);
    }
  }
  return found;
}

const files = walk(distDir).sort();

const parts = [];
parts.push("// Generated by web/gen-embed.js. Do not edit.");
parts.push('#include "Embedded.hpp"');
parts.push("");
parts.push("namespace wr {");
parts.push("");
parts.push("namespace {");
parts.push("");

const entries = [];
for (let i = 0; i < files.length; i++) {
  const bytes = fs.readFileSync(files[i]);
  const urlPath = "/" + path.relative(distDir, files[i]).split(path.sep).join("/");

  const chunks = [];
  for (let b = 0; b < bytes.length; b++) {
    chunks.push(bytes[b]);
  }
  const body = chunks.length === 0 ? "0" : chunks.join(",");

  parts.push("const u8 asset_" + i + "[] = {" + body + "};");
  entries.push({ urlPath, index: i, size: bytes.length });
}

parts.push("");
parts.push("} // namespace");
parts.push("");
parts.push("const embedded_asset EMBEDDED_ASSETS[] = {");
for (const entry of entries) {
  parts.push(
    '    {"' +
      entry.urlPath +
      '", asset_' +
      entry.index +
      ", " +
      entry.size +
      "},",
  );
}
parts.push("};");
parts.push("");
parts.push(
  "const usize EMBEDDED_ASSET_COUNT = " + entries.length + ";",
);
parts.push("");
parts.push("} // namespace wr");
parts.push("");

fs.writeFileSync(outFile, parts.join("\n"));
